// Package model provides Soro's persistence model primitives.
package model

import (
	"time"

	"github.com/google/uuid"
)

// Base is embedded by normal Soro models. IDs are generated by repositories as
// UUIDv7 values before lifecycle validation begins.
type Base struct {
	ID          uuid.UUID  `bun:"id,pk,type:uuid" json:"id"`
	Name        string     `bun:"name,type:varchar(255)" json:"name"`
	Description string     `bun:"description,type:text" json:"description"`
	Metadata    Metadata   `bun:"metadata,type:jsonb,notnull,default:'{}'" json:"metadata"`
	CreatedAt   time.Time  `bun:"created_at,type:timestamptz,notnull" json:"created_at"`
	UpdatedAt   time.Time  `bun:"updated_at,type:timestamptz,notnull" json:"updated_at"`
	DeletedAt   *time.Time `bun:"deleted_at,type:timestamptz,nullzero" json:"deleted_at,omitempty"`
	CreatedBy   *uuid.UUID `bun:"created_by,type:uuid,nullzero" json:"created_by,omitempty"`
	UpdatedBy   *uuid.UUID `bun:"updated_by,type:uuid,nullzero" json:"updated_by,omitempty"`
	DeletedBy   *uuid.UUID `bun:"deleted_by,type:uuid,nullzero" json:"deleted_by,omitempty"`
}

// SoroBase makes embedding Base an explicit repository contract.
func (b *Base) SoroBase() *Base { return b }

// Entity is implemented by pointers to structs that embed Base.
type Entity interface {
	SoroBase() *Base
}
