package generate

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestTransformersRunInOrderBeforeFormatting(t *testing.T) {
	generator := testGenerator(t)
	var visited []string
	if err := generator.UseTransformers(
		func(path string, content []byte) ([]byte, error) {
			visited = append(visited, "first:"+path)
			if strings.HasSuffix(path, ".go") {
				return append(content, []byte("\n// first\n")...), nil
			}
			return content, nil
		},
		func(path string, content []byte) ([]byte, error) {
			visited = append(visited, "second:"+path)
			if strings.HasSuffix(path, ".go") {
				return append(content, []byte("// second\n")...), nil
			}
			return content, nil
		},
	); err != nil {
		t.Fatal(err)
	}
	if _, err := generator.GenerateSerializer("User", []string{"email:string"}); err != nil {
		t.Fatal(err)
	}
	contents, err := os.ReadFile(filepath.Join(generator.Root, "app", "serializers", "user.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasSuffix(string(contents), "// first\n// second\n") {
		t.Fatalf("transformer output was not formatted/preserved:\n%s", contents)
	}
	want := []string{"first:app/serializers/user.go", "second:app/serializers/user.go"}
	if strings.Join(visited, ",") != strings.Join(want, ",") {
		t.Fatalf("visits = %v, want %v", visited, want)
	}
}

func TestTransformerFailureDoesNotWriteFiles(t *testing.T) {
	for name, transformer := range map[string]Transformer{
		"error":       func(string, []byte) ([]byte, error) { return nil, errors.New("custom failure") },
		"nil content": func(string, []byte) ([]byte, error) { return nil, nil },
		"invalid Go":  func(_ string, content []byte) ([]byte, error) { return append(content, []byte("not Go")...), nil },
	} {
		t.Run(name, func(t *testing.T) {
			generator := testGenerator(t)
			if err := generator.UseTransformers(transformer); err != nil {
				t.Fatal(err)
			}
			if _, err := generator.GenerateModel("User", []string{"email:string"}); err == nil {
				t.Fatal("expected transformation failure")
			}
			if _, err := os.Stat(filepath.Join(generator.Root, "app", "models", "user.go")); !os.IsNotExist(err) {
				t.Fatal("generator wrote a partial file after transformation failure")
			}
		})
	}
}

func TestTransformerCannotRemoveManagedMarker(t *testing.T) {
	generator := testGenerator(t)
	if err := generator.UseTransformers(func(path string, content []byte) ([]byte, error) {
		if strings.HasSuffix(path, "routes.go") {
			return []byte(strings.TrimPrefix(string(content), "// Code generated by Soro. DO NOT EDIT.\n")), nil
		}
		return content, nil
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := generator.GenerateResource("User", []string{"email:string"}); err == nil || !strings.Contains(err.Error(), "managed marker") {
		t.Fatalf("expected managed marker error, got %v", err)
	}
	if _, err := os.Stat(filepath.Join(generator.Root, "app", "models", "user.go")); !os.IsNotExist(err) {
		t.Fatal("resource generation wrote partial output")
	}
}

func TestUseTransformersValidation(t *testing.T) {
	var generator *Generator
	if err := generator.UseTransformers(func(string, []byte) ([]byte, error) { return nil, nil }); err == nil {
		t.Fatal("expected nil generator error")
	}
	generator = testGenerator(t)
	if err := generator.UseTransformers(nil); err == nil {
		t.Fatal("expected nil transformer error")
	}
}

func testGenerator(t *testing.T) *Generator {
	t.Helper()
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/test\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	generator, err := Open(root, false)
	if err != nil {
		t.Fatal(err)
	}
	return generator
}
